### ISSUE TITLE
Setup to compile

### ISSUE THREAD

**Issue by Takicegek** [metalicjames/CryptoCurrency#1]
Hello what are the steps to build on windows or unix?

**Comment by metalicjames** [comment]
I have added some instructions to the readme file.

**Comment by Takicegek** [comment]
Cheers mate. btc address for a tip?

**Comment by metalicjames** [comment]
No problem. 

19SdW1xSPRt3wXaLRjB986Fc6iVJequSPN

**Comment by Takicegek** [comment]
I get this error when compiling on ubuntu, also tip sent
followed the readme and compiled cryptokernel without issues 

root@node:~/CryptoCurrency# ./build.sh
g++ -Wall -std=c++14 -O2 -c main.cpp -o main.o
g++ -Wall -std=c++14 -O2 -c protocol.cpp -o protocol.o
g++ -Wall -std=c++14 -O2 -c wallet.cpp -o wallet.o
g++ -Wall -std=c++14 -O2 -c rpcserver.cpp -o rpcserver.o
g++ main.o protocol.o wallet.o rpcserver.o -o CryptoCurrency -lCryptoKernel -ljsoncpp -pthread -lenet -lcrypto -lleveldb -lmicrohttpd -ljsonrpccpp-common -ljsonrpccpp-server -lcurl -ljsonrpccpp-client -ldl
//usr/local/lib/libCryptoKernel.a(crypto.o): In function `CryptoKernel::Crypto::getPublicKey[abi:cxx11]()':
crypto.cpp:(.text+0x1b1): undefined reference to`EC_KEY_key2buf'
//usr/local/lib/libCryptoKernel.a(crypto.o): In function `CryptoKernel::Crypto::getPrivateKey[abi:cxx11]()':
crypto.cpp:(.text+0x294): undefined reference to`EC_KEY_priv2buf'
//usr/local/lib/libCryptoKernel.a(crypto.o): In function `CryptoKernel::Crypto::setPublicKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
crypto.cpp:(.text+0x3b6): undefined reference to`EC_KEY_oct2key'
//usr/local/lib/libCryptoKernel.a(crypto.o): In function `CryptoKernel::Crypto::setPrivateKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
crypto.cpp:(.text+0x484): undefined reference to`EC_KEY_oct2priv'
collect2: error: ld returned 1 exit status

**Comment by metalicjames** [comment]
You need to install the latest development version of OpenSSL. It's possible you already have a previous version installed though which is causing problems. Can you try:
`sudo apt-get remove libssl-dev`

and retry?

**Comment by Takicegek** [comment]
That fixed it cheers!

**Comment by Takicegek** [comment]
Sent you an email

**Comment by juscamarena** [comment]
Had this issue as well, but worked out doing the apt-get remove
